### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-webdriver#29]
```
import Data.Either (Either())
import Data.Maybe (Maybe())
import Data.Foreign (Foreign())
import Data.Maybe.Unsafe (fromJust)
import Data.Either (either)
```

`Unknown type Either`

**Comment by jonsterling** [comment]
Hmmm... I wiped out my cached builds and ran 

```
bower install
gulp
```

and it seemed to build fine. Is there another thing I can try for reproducing?

**Comment by beckyconning** [comment]
Its breaking when compiling SlamData with this as a bower dependency on psc 0.7.2.

**Comment by beckyconning** [comment]
gulp didn't reproduce the error for me either. neither did travis fail. maybe gulpfile is set up incorrectly?

**Comment by jonsterling** [comment]
@beckyconning Interesting. I take it I should be able to reproduce on SlamData @ master? Or what should I do in order to reproduce it?

**Comment by cryogenian** [comment]
we use `0.7.2`. It can use only one import.

**Comment by beckyconning** [comment]
Gulp succeeded for me on 0.7.2 though.
