### ISSUE TITLE
support file detectors

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-webdriver#9]
This is needed in order to test uploading files with Sauce Labs. When a address of a local file on the host (i.e. your machine) is entered in, that file will be sent over the wire to the remote client and dealt with seamlessly.

Although it is not part of the builder API in the JS webdriver library, so far as I can tell, it may be possible for us to include it in our own builder API.

**Comment by jdegoes** [comment]
:+1:

**Comment by jonsterling** [comment]
Some not-so-great news: it looks as though the JS API doesn't yet support remote file detectors properly; though this is surprising to me given what I saw in the documentation. I have asked on the Selenium mailing list for clarification, and will update this ticket when I have more information.

**Comment by jonsterling** [comment]
I added support for file detectors in #12
